"""Domain models shared across the Teams AI Planner."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Iterable, List, Optional


@dataclass(slots=True)
class TeamsMessage:
    """Represents a normalized Microsoft Teams channel message."""

    id: str
    sender: str
    content: str
    created_at: datetime
    mentions: List[str] = field(default_factory=list)

    @classmethod
    def from_graph(cls, payload: dict[str, Any]) -> "TeamsMessage":
        body = payload.get("body", {})
        content = body.get("content", "").strip()
        sender = (
            (payload.get("from", {}) or {})
            .get("user", {})
            .get("displayName", "Unknown")
        )
        created_at = datetime.fromisoformat(
            payload.get("createdDateTime", datetime.utcnow().isoformat().replace("Z", ""))
        )
        mentions = [
            mention.get("mentioned", {})
            .get("user", {})
            .get("displayName", "")
            for mention in payload.get("mentions", [])
        ]
        mentions = [m for m in mentions if m]
        return cls(
            id=payload.get("id", ""),
            sender=sender,
            content=content,
            created_at=created_at,
            mentions=mentions,
        )


@dataclass(slots=True)
class ProposedAction:
    """Action generated by the AI analyzer."""

    title: str
    details: str
    urgency: str = "normal"
    recommended_recipient: Optional[str] = None
    suggested_message: Optional[str] = None
    related_message_id: Optional[str] = None


@dataclass(slots=True)
class ActionPlan:
    """Collection of AI-generated actions for the day."""

    generated_at: datetime
    timespan_hours: int
    message_sample_size: int
    actions: List[ProposedAction]

    def to_dict(self) -> dict[str, Any]:
        return {
            "generated_at": self.generated_at.isoformat(),
            "timespan_hours": self.timespan_hours,
            "message_sample_size": self.message_sample_size,
            "actions": [
                {
                    "title": action.title,
                    "details": action.details,
                    "urgency": action.urgency,
                    "recommended_recipient": action.recommended_recipient,
                    "suggested_message": action.suggested_message,
                    "related_message_id": action.related_message_id,
                }
                for action in self.actions
            ],
        }


def ensure_messages(payloads: Iterable[dict[str, Any]]) -> list[TeamsMessage]:
    """Normalize raw Graph payloads into :class:`TeamsMessage` objects."""

    return [TeamsMessage.from_graph(payload) for payload in payloads]
